from typing import Any, Iterator, Optional, Type


class CommodityTracker:
    def get_statistic(self, stat_type: Type[Any], add: bool = ...) -> Optional[Any]: ...
    def set_value(self, stat_type: Type[Any], value: float, **kwargs: Any) -> None: ...
    def get_value(self, stat_type: Type[Any]) -> float: ...
    def __iter__(self) -> Iterator[Any]: ...
