from typing import Iterator, Optional, ValuesView
from sims.sim_info import SimInfo

class SimInfoManager:
    def values(self) -> ValuesView[SimInfo]: ...
    def __iter__(self) -> Iterator[int]: ...
    def get(self, sim_id: int) -> Optional[SimInfo]: ...
