from typing import Optional

from clock import GameClock
from sims.sim_info import SimInfo
from sims.sim_info_manager import SimInfoManager
from zone import Zone

def sim_info_manager() -> SimInfoManager: ...
def current_zone_id() -> Optional[int]: ...
def current_zone() -> Optional[Zone]: ...
def active_lot_id() -> Optional[int]: ...
def active_sim_info() -> Optional[SimInfo]: ...
def game_clock_service() -> GameClock: ...
