from typing import Optional
from clock import GameClock
from sims.sim_info_manager import SimInfoManager

def sim_info_manager() -> SimInfoManager: ...
def current_zone_id() -> Optional[int]: ...
def active_lot_id() -> Optional[int]: ...
def game_clock_service() -> GameClock: ...
